### PR TITLE
Finalization of the backend part

### PR DESCRIPTION
**Pull request by eric-bel**
We, the developers, were told that we needed to complete the backend part by Monday (until March 28, 2022).
This Pull Request is made for this.

### CODE REVIEW

**Comment by eric-bel** [comment]
made the basics for the backend part
needs to be improved, but a little later

**Comment by eric-bel** [comment]
still fixing the backend part

**Comment by eric-bel** [comment]
Changes from this branch will be included in the pull request for the next homework

**Comment by devbarden** [comment]
> Changes from this branch will be included in the pull request for the next homework

in this case please declined this PR

**Pull request merged**
